### ISSUE TITLE
Change Attention and Positional Embedding Calculations to FP32

### ISSUE THREAD

**Issue by rtaylor-rx-m** [dingo-actual/om#8]
As described in https://arxiv.org/abs/2411.13476, the RoPE offsets are incorrectly calculated when using FlashAttention-2 with BF16. For now, the simplest fix is to carry out attention and embedding calculations in FP32 then downcast back to BF16 after.

It's probably worthwhile to make sure there aren't any special considerations that need to be addressed concerning Accelerate's mixed-precision training.

**Comment by dingo-actual** [comment]
Fixed.
